name: Deploy site to Pages

on:
  push:
    branches: ["main"]
  # enable manual build
  workflow_dispatch:

# set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: EA
      - name: Build project
        run: mvn verify --no-transfer-progress
      - name: Build site
        run: java --enable-preview -cp "app/*" zone.nox.Main build --target global
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
